version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: faceit
    volumes:
      - ./faceit.sql:/docker-entrypoint-initdb.d/faceit.sql

